---
title: Turning down the noise
author: ~
date: '2018-08-02'
slug: turning-down-the-noise
categories: []
tags: []
description: |
  More information about managing depression and anxiety.   
output:
  distill::distill_article:
    self_contained: true
---

I'm still in the process of recovering from my current bout of depression and anxiety. I'd like to talk about what is currently helping me moderate my anxiety. I have been practicing mindfulness and meditation for the past three years and I'm beginning to realize how necessary it is in our information dense age. Many of my symptoms of anxiety are really from an information overglut.

I'm currently on way too many projects and am teaching as well. Everything wants my attention. We need to decide dates for a visit, etc. Booking travel, grading students, etc. The noise of academic life can be overwhelming and can prevent me from working effectively. A book I'm reading, *Real Happiness at Work* by Sharon Salzberg, talks about Attention Deficit Trait disorder:

> Attention deficit trait (ADT) is workplace-induced attention deficit caused by the constant, relentless input of information, these days usually enabled by our high-tech devices, smartphones, and computers.

This is especially prevalent for people like me who are on multiple grants and have many collaborators. I'm okay with putting out the occasional fire or dealing with an emergency deadline; if I believe in the project, I can muster the energy. However, the problem is when I have multiple fires to deal with from multiple people. The task switching leads to stress and leads to an inability to prioritize. This is where I've been the last few months.

And this is when the voices of doubt begin to fuel my anxiety. On top of the enormous task list, there's the feelings of failure and disappointment because I can't get simple things done. In my head the voices reach a frenzy, a cacophony, a noise. And then I can't think straight, prioritize, work on one thing.

What is the solution to ADT and the noise of life? Mindfulness and unitasking. As Sharon Salzberg notes:

> ... while it’s unrealistic to try to stop the number and variety of incoming demands, in our technologically advanced world it is possible to modulate how much information we’re taking in, and how many tasks we are doing at once. When we slow down and concentrate on doing just what is before us to be done now, **we become the masters of our own environment rather than its frantic slaves.**

This idea (being a master of my environment) appeals to me in the midst of my academic anxiety. Practicing mindfulness (through daily meditation) helps me to focus on the here and now. We are wired to ruminated about the past (things we wish we'd done better) or the future (oh crap, I need to prepare upcoming stuff). Meditation is all about building that focus and attention on what's before us. If we can't do it all, we can at least work on what's right in front of us.

I've also been reading Anne Lamott's *Bird by Bird*, a book reflecting on the hows and whys of writing and living your life while doing it. It's a sobering view of why we write and how to keep on in the face of numerous adversities. There's one passage that really resonated with me in the chapter called "Shitty First Drafts" in dealing with the incessant chatter of life:

 > Close your eyes and get quiet for a minute, until the chatter starts up. Then isolate one of the voices and imagine the person speaking as a mouse. Pick it up by the tail and drop it into a mason jar. Then isolate another voice, pick it up by the tail, drop it in the jar. And so on. Drop any high maintenance parental units, drop in any contractors, lawyers, colleagues, children, anyone else who is whining in your head. Then put the lid on, and watch all these mouse people clawing at the glass, jabbering away, trying to make you feel like shit because you won't do what they want - won't give them more money, won't be more successful, won't see them more often. Then imagine there is a volume control button on the bottle. Turn it all the way up for a minute, and listen to the stream of angry, neglected, guilt-mongering voices. Then turn it all the way down and watch the frantic mice lunge at the glass, trying to get to you. Leave it down, and get back to your shitty first draft.

This is another idea in mindfulness: *welcoming and acknowledging our worries and negative voices*. If we ignore or refuse these feelings, they just become stronger and louder in the din and the noise. I have all sorts of these feelings: *I don't work hard enough*, *I'm a failure*, *I'm letting down people who depend on me*, *Everyone is out there working on cooler things than me*. Now I'm trying to take an effort to welcome these feelings into my mental space, saying "okay, I hear you and acknowledge you, so you don't have to be yelling anymore". And surprisingly, they do quiet down. Acknowledging the feelings of failure, thanking them for their contribution to the discussion and showing them the door is important. As Kelly Boys says in *The Blind Spot Effect*:

>If you approach life with a willingness to be with what you encounter without getting lost in it, it moves gracefully within your experience.

And that helps lower the volume and free your attention.

If you are feeling generalized anxiety or attention deficit trait, I encourage you to look into mindfulness as a way of turning down the noise. 

## Resources

These are some of the resources that I've used when writing this post. 

+ [*The Mindful Geek: Secular Meditation for Smart Skeptics*](https://www.amazon.com/gp/product/0692475389/) by Michael Taft. This is a great book for people who are interested in Mindfulness and the psychological and neuroscience research about why mindfulness works in reducing depression and anxiety. I started here. Michael Taft calls meditation "a technology for hacking the human wetware to improve your life". 
+ [*Real Happiness at Work: Meditations for Accomplishment, Achievement, and Peace*](https://www.amazon.com/Real-Happiness-Work-Meditations-Accomplishment/dp/B0182Q7KAQ/) by Sharon Salzberg. This is a nice followup to *Mindful Geek*, talking about how we can regain control in our workplace.
+ [*The Blind Spot Effect: How to Stop Missing What's Right in Front of You*](https://www.amazon.com/Blind-Spot-Effect-Missing-Whats-ebook/dp/B07413Q5Y7/) by Kelly Boys. I am really liking this book so far. It's about how meditation and mindfulness can help us find our cognitive blind spots and move beyond them. 
+ [*Bird by Bird: Some Instructions on Writing and Life*](https://www.amazon.com/Bird-Some-Instructions-Writing-Life/dp/0385480016/) by Anne Lamott. I recently started reading this on vacation. Writing can be a lonely and solitary life, and I find many of her suggestions about living to apply equally well to research. 
