project:
  type: website
  output-dir: docs

execute: 
  freeze: true

website:
  title: "Ted Laderas, PhD"
  google-analytics: "G-SKN5BS6ZBZ"
  description: "Ted's R and Teaching Blog"
  navbar:
    right:
      - teaching.qmd
      - articles.qmd
      - blog.qmd
      - talks.qmd
      - icon: github
        href: https://github.com/laderast/
      - icon: mastodon
        href: https://mastodon.cloud/@tladeras/
      - icon: twitter
        href: https://laderast.github.io/tweets/
  twitter-card: 
    card-style: summary
    creator: "@tladeras"
format:
  html:
    embed-resources: true
    link-external-icon: true
    link-external-newwindow: true
    theme: lux
    css: styles.css
