project:
  type: website
  output-dir: docs

execute: 
  freeze: true


website:
  title: "Ted Laderas, PhD"
  google-analytics: "G-SKN5BS6ZBZ"
  description: "Ted's R and Teaching Blog"
  site-url: https://laderast.github.io/
  navbar:
    right:
      - consulting.qmd
      - teaching.qmd
      - articles.qmd
      - talks.qmd
      - newsletter.qmd
      - icon: rssd
        href: index.xml
      - icon: github
        href: https://github.com/laderast/
      - icon: mastodon
        href: https://vmst.io/@tladeras
      - icon: twitter
        href: https://laderast.github.io/tweets/
  twitter-card: 
    card-style: summary
    creator: "@tladeras"
format:
  html:
    embed-resources: true
    link-external-icon: true
    link-external-newwindow: true
    theme: lux
    css: styles.css
