---
title: "Curriculum Vitae"
description: |
  Curriculum Vitae for Ted Laderas.
date: "`r Sys.Date()`"
output: 
  distill::distill_article:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

**Assistant Professor**, Division of Bioinformatics and Computational Biology, Department of Medical Informatics and Clinical Epidemiology, Oregon Health & Science University.

**Researcher**, OHSU Knight Cancer Institute, Oregon Health & Science University

My research focus is on the Systems Biology of Complex Diseases. I use integrative modeling approaches across OMICs types to achieve this.

I am also passionate about teaching students to think about data, and have taught Data Science to a variety of groups, including graduate students, post-docs, staff, and clinicians. I am also an RStudio Certified Trainer in both the [Tidyverse](https://www.tidyverse.org/) and [Shiny](https://shiny.rstudio.com).

# Teaching and Education

## Teaching Statement

I believe in democratizing data science. To this end, I have been involved with several national educational efforts: Big Data to Knowledge, National Library of Medicine’s efforts with data science. My workshops, lectures and lessons have been utilized at multiple schools, and by multiple audiences, including clinicians, bioinformaticians, undergraduates.

I utilize evidence-based pedagogical techniques in my teaching, specifically active learning and [psychological safety](https://laderast.github.io/psych_safety). I am a firm believer in making students feel psychologically safe and giving them space to be curious. Many of my students have become collaborators in my teaching materials, improving them with their ideas and their questions. As a result, my work has been recognized as being accessible to a wide audience.

I believe that we must give graduate students more transferable skills outside of academia, and so I have co-founded [BioData Club](https://biodata-club.github.io), a community of practice at OHSU and beyond that focuses on teaching and learning data science skills. I am dedicated to my students, and courses and workshops show consistently high ratings and evaluations. I am also a certified instructor for both The Carpentries and RStudio.

In my educational work, I have focused on [Exploratory Data Analysis (EDA)](https://laderast.github.io/burro) as a way to be curious and to not be afraid of your data. I have taught Predictive Modeling and Data Analytics, interactive visualization, Open Science, Team Science, and the importance of interdisciplinary collaboration. I am dedicated to making my work accessible and reproducible by others.

## Courses/Workshops

### [BSTA504: R Programming](https://sph-r-programming.netlify.app)

### [BMI507: Ready for R](https://ready4r.netlify.app)

### [BMI569: Data Analytics]()

### []

## Selected Educational Scholarship