---
title: "My Time at PositConf 2023"
---

# My Time at PositConf

Well, it’s been over a week since I got back from PositConf. While the new features and geegaws from Posit are of interest (including Shinylive for R), as well as the workshops, I’ve found that PositConf is much more about the supportive R community. I reconnected with a lot of people, and found even more people to hang out with. It’s just what I needed to recharge after a long year of bullshit come my way.

## First, the Technical Cool Stuff

The biggest announcement this year was [Shinylive for R](); development of WebR (a version of R compiled to Web Assembly, which enables running R directly in a web browser) has progressed to the point that we can now run Shiny Apps in the Browser. With the webR-quarto extension, you can now run shiny apps in the browser. 

Their behavior is not quite like running Shiny from your computer or Shiny Server; ShinyWebR apps don’t really have their own filesytem as of yet. Similarly, you need to install packages using `webr::install()`to install the web assembly compiled packages rather than `install.packages()`.

A lot of changes in the `tidyverse` were evolutionary. One welcome change in `dplyr` was to the `group_by()/summarize()` pattern. `summarize()` now supports a `{data.table}` like syntax for grouping so you don’t have to `ungroup()` at the end. 

GitHub Copilot is now available in RStudio/Posit Team. 

## Workshops: Didn't go this year, but great topics

I didn't TA for the workshops this year, but there were some great topics:



## The Conversations and Hanging Out

The best part about the conference was hanging out with the Data Science Hangout (DSH) crew: Rachael Dempsey, Mike K Smith, Libby Heeren, Marlene, Donald, Jadey Ryan, Natalia, Marcos Huerta, Samir. It was really fun going to each other’s talks and supporting each other. Here are a few highlights:

- Jadey Ryan had the very last timeslot, but made the most of it by talking about parametrized quarto reports, with conditional code blocks
- Libby Heeren gave a great lightning talk about making Data Friends and how co-working together is an easy way to make data friends
- Marcos Huerta implemented a web app in three different Python Frameworks: Shiny for Python, Streamlit, and Plotly Dash. It was really cool to compare what was easy and what was hard.
- Lydia Gibson gave a great talk about the R for Data Science group and 

We had a nice reception at three dots and a dash, a Tiki Speakeasy, and it was great to meet so many of the the DSH people in person, like Daniel Sjoberg and Travis Gerke. 

## My Talk and Others

[My talk](https://laderast.github.io/meetup_burnout/) was about overcoming burnout as a data science meetup organizer and building a sustainable community of practice. Writing and researching it has been an amazing journey, serving as an excuse to reconnect with lots of people (Kate Hertweck, Julia Stewart-Lowndes, Jon Harmon) and meet an amazing group of [community organizers](https://colorado.posit.co/rsc/ds-community-builder/) and pick their brains for my talk. Through talking with them, I discovered three themes that I based my talk around: Self Care, Building a Core Group, and Making Your Meetup Welcoming.

Parallel to researching the talk was writing the talk which I did with some coaching from Articulation, which was provided to all speakers. It took me on an amazing journey, with several other speakers, from formulating the essential question to the final presentation. I decided to do something risky and make hand-drawn slides, which I was afraid would be too simplistic, but I heard connected with the majority of people.

As for giving the talk, I was nervous, but the session was really supportive and low-key. I'm happy with how it went, and how it was a nice journey from researching and conceiving the talk to giving it. It was a pleasure to share a session with Riva, Kari, and Millie, all sharing their data science experiences and learning along the way. I especially loved Kari’s talk about how Black Hair is like Data Science (both complex, and [require some care to untangle] and show their true form). She’s always an inspiring speaker. Riva gave a talk about how R-Ladies Global is moving forward, becoming more modular, to support the core members and avoid burnout. Finally, Millie gave a talk about starting her blog 

More this year, I’ve felt connected to the new users of R and I want to see them do amazing things. And I’m grateful that I’m invited to go along with them on their journey. I plan on giving more talks like this where I plan on interviewing people. I never thought I'd like qualitative research, but it fits me. 
