---
title: "Moving On and Upwards"
description: |
  I'm leaving OHSU. The reasons why.
date: 04-29-2021
output:
  distill::distill_article:
    self_contained: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

I'm leaving OHSU. I have accepted a position to become a bioinformatics trainer for DNANexus. I am passionate about making sure that people do good analysis, and I'm convinced that DNANexus is the best place for me to make an impact and move away from academia.

As an bioinformaticist/collaborator who is focused on doing reproducible analysis, the level of financial support I received in academia was difficult to sustain. I didn't have an R01 of my own; I was often divided between multiple projects where I was faced with the decision of having to triage work and do work I was less proud of. I was spending less time on things I'm passionate about, and more on administration, which was much less important to me. I was also split between multiple departments and meeting the expectations of everyone was way too difficult for me.

Having multiple bosses, I was also forced to adopt the survival strategy of not disappointing the same person in a row. I never felt good about that, and I'm tired of feeling that way. I could not see my career as being sustainable, nor did I ever consider myself someone who would be promoted in the current environment. The university did not recognize the level of collaboration that I dedicate myself to, nor does it priortize this level in terms of promotion and tenure criteria. So I never felt sure whether I was on the path to promotion. 

A lot of what I've tried to accomplish has been fueled by a deep anger by what happened to me during my dissertation process. My dissertation advisor was unsupportive and I had a toxic dissertation committee. But I can't make these feelings the cornerstone of my future life. 

I've tried to make academia less painful through efforts such as Cascadia-R, BioData Club, and my workshops and courses. I still believe that learning should be less lonely and that fighting impostor syndrome is something that should be done in a supportive community. I will continue to be involved with both in a limited capacity. 

I will always be grateful to my students and TAs for their fresh perspectives and energy. I hope you will continue on with that enthusiasm. I hope that I have inspired you, at least in a small way. I am also grateful for all the faculty, staff, postdocs, and everyone in the open science, data science and R communities who have been supportive of me in my journey, and who have helped me arrive at this decision.

I don't want my decision to be an example for others. I don't want to discourage others in their pursuit of an academic career, if that is what their heart is set on. But please be aware of the potential downfalls of such a path. The high rejection rates for funding. The low percentage of us who are destined for stable careers in academia. You need to find your own way, and you will probably do a better job of finding funding than I did. Get to independence through securing your own funding as fast as possible, or start building those marketable skills. 

In the coming months, I will probably release less R material, due to my focus on bioinformatics training. I love R, but I have given more than I have recieved back and I need to focus on myself for the time being. I've depleted myself over the last year and I need to recharge. Hopefully you will respect that.
