---
title: "A Good Son to a Bad Dad"
date: 6/20/2023
---

> Note: I have some misgivings about posting this, but I'm hoping it will help others to realize that they're not defined by their parents. Not everyone is blessed to have good parents.

When my dad died in March, one of his relatives I notified called me "a bad son" and that I owed him more.

To that, I ask, *what does it mean to be a good son to a bad dad?*

Our relationship was complicated. My dad was a textbook narcissist, and his siblings all resented him for the special treatment he got from his father. The more I have learned about narcissism, the more I think his life was sad, but also the more I am aware of the damage he did to the rest of my family.

Narcissists thrive on making others feel bad, because it's a power move that makes them feel better. But underneath it all lies a very insecure and emotionally stunted person who lashes out. They need external validation, and to be adored. Inevitably, they burn bridges and lose relationships. 

I remember him saying that the reason to go to college was to learn how to manipulate people. 

I remember him gaslighting me, making me unsure of myself. 

The only way to "win" with narcissists is to not play their games, and we have to protect ourselves, whether that be to leave them, [grey rock them](https://www.psychologytoday.com/us/blog/the-time-cure/202211/when-dealing-narcissist-the-gray-rock-approach-might-help#:~:text=In%20a%20nutshell%2C%20the%20gray,rock%E2%80%9D%3A%20dull%20and%20boring.), or emotionally armor ourselves from their criticism. 

To answer the question, I think that my dad provided a counter example of what I didn't want to become. I think that's the only way to be good son in this situation. 

My number one value is kindness. But my number two value, learned the hard way, is self-preservation. I don't have to be vulnerable or share parts of my life to people who would weaponize it against me. 

So next time you criticize someone for being a bad family member for not being present, know that it's probably a survival mechanism. That your criticism and shaming is enabling the narcissistic cycle to begin again.

I have blocked those negative family members from my life. They can take their criticism elsewhere.

## Resources

If you suffered narcissistic abuse, there are two YouTube channels I highly recommend: [Dr. Ramani](https://www.youtube.com/@DoctorRamani) and [Surviving Narcissism with Dr. Les Carter](https://www.youtube.com/@SurvivingNarcissism). Watching these has helped me make sense of my life. Please seek therapy if you need it. 