---
title: "Why Communities of Practice are Important for your Organization"
---

I've done my most productive learning in a group of like-minded individuals who also want to learn. We challenge each other and we help each other out; there is accountability. These groups are known as a *communities of practice*. Research again and again shows that learning together in a community of practice is highly effective. 



## Why do communities of practice work? 

> Learning is a matter of engagement: it depends on opportunities to contribute actively to the practices of communities that we value and that value us, to integrate their enterprises into our understanding of the world, and to make creative use of their respective repertoires … Practice is a process of interactive learning [that] enables newcomers to insert themselves into existing communities. It is the learning of mature members and of their communities that invites the learning of newcomers (277). [https://www.fairborninstitute.org/community-of-practice]

