---
title: "Best Practices on the DNAnexus Platform"
date: 09-10-2023
categories: ["ukbiobank", "dnanexus", "best-practices", "webinar", "free"]
---

This is an online and free textbook that covers essential skills and best practices for working on the DNAnexus platform.

It covers the following topics:

- Introduction to Object Oriented Filesystems
- Project and File Management on the DNAnexus Platform
- Utilizing Spark on the DNAnexus Platform
- Extracting Phenotypic Data on the DNAnexus Platform
- Working effectively with Hail on the DNAnexus Platform

# Links

[Book](https://laderast.github.io/best_practices_dnanexus/){.btn .btn-primary role="button"} [Repository](https://github.com/laderast/best_practices_dnanexus){.btn .btn-primary role="button"}


## Learning Objectives

-   **Apply** bash scripting to your own work
-   **Articulate** basic Cloud Computing concepts that apply to the DNAnexus platform
-   **Leverage** bash scripting and the dx-toolkit to execute jobs on the DNAnexus platform
-   **Execute** batch processing of multiple files in a project on the DNAnexus platform
-   **Monitor**, **profile**, **terminate** and **retry** jobs to optimize costs
-   **Manage** software dependencies reproducibly using container-based technologies such as Docker

