---
title: A Introvert's Survival Guide to Conferences
author: ~
date: '2018-05-17'
slug: a-introvert-s-survival-guide-to-conferences
categories: [social, networking]
tags: [introverts, conferences, survival]
description: |
   Are you an introvert? Here's how to make conferences easier.   
---

In academia, it’s inevitable to have to travel and present at conferences and meetings. As an introvert, I've been trying to compile a few tips that have helped me navigate large conferences so I don’t feel overwhelmed. 

It is unfortunate that though the academic community has many introverts, conference and meeting structure is heavily biased towards extroverts. (No offense to extroverts, but some of you can sometimes seem like blowhards to us introverts.) 

The question for introverts is how to connect with people at meetings while being true to our nature. We value meaningful and deep connections rather than shallow ones.

1. **Set Yourself Up For Success. Be prepared.** If you can, try to connect with people or identify the people you want to meet before the conference even starts. Bring things that make you comfortable. A sweater, water, candy/energy bars. If there are sessions that look interesting, look at the author’s previous papers and think of questions beforehand. An introvert’s strength is that they are good at preparing for things. Use that preparation to your advantage.

1. **Be Curious, Not Scared.** You are a curious person. If you weren’t, you wouldn’t be in science. Use that curiosity to connect. Wonder about things. Think about where research could go.

1.  **Be the Host, Not the Hosted**. According to Susan Cain, introverts do very well socially when they have a specific role. I like moderating sessions for this reason. I’m pretty good at being amiable and making other people comfortable in such situations. By being thoughtful and helping people with their problems, you can form connections.

1. **It’s Totally Ok to Take a Break**. It’s called self-care. Remember, introverts find social situations draining. Go outside for a few minutes, or find a corner that’s quiet and secluded, look at websites on your laptop. Just don’t withdraw. It’s a break, not a jailbreak.

1. **Accept That You’ll Miss Out. Emphasize quality over quantity.** As an introvert, I am constantly feeling guilty about not going to every session and meeting people. FOMO can drive me to the point of being overwhelmed. But the truth is, if I can meet two or three people that I can connect with and two or three talks I find inspiring, I consider that a good meeting.

1. **Make Yourself Comfortable at Social Functions**.  Introverts can do very well socially when the situation is proscribed and the roles are clear, which is why I like poster sessions. There’s a limited set of questions you can ask and be asked. You can also do your homework by looking at the posters before you meet the person. Also: I hate asking public questions in meetings. (This again, is where extroverts can sometimes seem like blowhards to me. Bless their hearts.) I really prefer to go up to the speaker afterwards and try to have a meaningful conversation. 

1. **Remember That Most People Are Equally Nervous. Be kind.** Be compassionate to yourself and to others. This will make you more relatable. When you focus on making others comfortable, you concentrate less on your own nervousness. Kindness goes a long way in these situations. Help someone out who’s struggling. 

1. **Ask Questions and Listen**. Again, other people at conferences want to be heard and connect. You may run into raging egotists who don’t listen to you. It’s ok to politely disengage from the conversation. But there is something always interesting about everyone.

1. **Gauge When You’re Exhausted**. As an introvert, being with people can be draining. At some point, enough is enough. Take the evening off, grab something to go, and watch tv or read a book in your hotel room alone. It’s ok, no one is keeping score of how many social events you are going to. Again, it’s ok to not go to the big reception (unless you’re giving a poster at that time, of course). 

1.  **It’s OK, the Right People Will Like You**.  You will eventually find people you want to talk to. Nurture these relationships. If someone gives you their card, follow up on it. It’s a sign of wanting to make connections.

1. **Don’t Expect The World of Each Social Interaction**. I think sometimes we idealize what our perfect interaction would be. We get disappointed when our interactions are less than that. Prepare to be pleasantly surprised, but don’t get bored and wander off. Respect goes a long way, and also serendipity is good. Try to learn more outside your field.

1. **It’s Totally Okay to be Awkward**. Just own it. Most scientists are awkward in some way.  (I know that I am, stop denying it people.) Being awkward is a way of being vulnerable - and being vulnerable is a way of connecting. I sometimes consider wearing an “I’m an introvert” button at conferences. At least it would be a good conversation starter. So go ahead, wear something quirky that you like. It can serve as a signal to find like minded people. Remember, own your awkwardness.

1. **Breathe**.  Conferences can feel like scary and unsafe situations to introverts. If you feel agitated, don’t force it. Take a moment and breathe. 

The world of conferences doesn’t really value introverts, but it needs us (at least there are some people thinking about [making conferences more introvert friendly](https://scientistseessquirrel.wordpress.com/2018/03/15/making-a-conference-introvert-friendly/)). We’re thoughtful, slow to react, but we can synthesize and bring deeper understanding. Give us space to think and be ourselves, and we will contribute and add diversity to the conversation. 

## For more information

There are lots of blogs written about this. Here are some of my favorites.

- [How to Make the Most of a Conference as an Introvert](https://www.theconfusedmillennial.com/conference-introvert/)
- [How to Survive Big Conferences As an Introvert](https://www.lifehack.org/articles/communication/how-to-survive-big-conferences-as-an-introvert.html)
- [How Introverts can Make the Most of Conferences](https://hbr.org/2015/10/how-introverts-can-make-the-most-of-conferences)

