---
date: '2015-11-19'
title: Statcheck Interview
description: |
   Interesting interview with the developer of statcheck
tags: [rstats]
output:
  distill::distill_article:
    self_contained: true
---

Due to the usual postdoc busy-ness, I haven't had the energy to update this blog as much as I would like, but I thought [this interview on Retraction Watch](http://retractionwatch.com/2015/11/17/making-it-easier-and-more-automated-to-find-errors-a-guest-post-from-the-co-developer-of-statcheck/#more-34435) from Michèle B. Nuijten, the developer of the R-package statcheck to be fascinating. Her package essentially automates the checking of p-values given published data in papers, from converting the papers from pdf to text, and sees if the calculated p-values are correct. There was a lot of trial and error in parsing known formats for p-values, but now the package is available.

I see an potentially really interesting master's thesis in forensic bioinformatics in using the package to assess reproducibility of results in a field. Note that the student probably wouldn't make any friends in high places, but it would be a potentially high impact thesis.