---
title: Kindness at the Cost of Yourself
date: '2019-09-23'
slug: kindness-at-the-cost-of-yourself
categories: [self-care]
tags: [self sacrifice]
description: |
   Being overdrawn at the bank of kindness and self-care.   
output:
  distill::distill_article:
    self_contained: true
---

 > In healthy cultures, people rise by elevating others and fall by undermining others. In toxic cultures, people are forced to choose between helping others and achieving success. Choose the workplace where success comes from making others successful. - Adam Grant

When I read Adam Grant’s [*Give and Take*](https://www.adamgrant.net/give-and-take), it was like a light went off. In this book, Grant gives profiles of highly successful people who are givers - people who have changed their field by making things better for others. I immediately connected to this idea of giving. Here was a way to network with people that really worked for me. Giving and connecting people are what I do best. I like to help people achieve their goals if I know someone else who can help them.

And no doubt, embracing my identity as a giver has helped change my career trajectory - in the last few years, I co-founded [Cascadia R](http://cascadiarconf.com), produced the [R-Bootcamp](http://r-bootcamp.netlify.com) with Jessica Minnier, and have met so many people in the field of education and open science that I want to work with and who have inspired me. 

However, as I’ve noted before, I tend to be giving to the point of being self sacrificing, which is not good. I’m reminded of the end of Kafka’s *Metamorphosis* when (spoilers) as Gregor Samsa dies in his bug form. As he dies, he worries about the agency of his family. Will they be able to support themselves? In the end, the family that he was worried about finds jobs, support themselves and thrive in the end. Without him. One interpretation of this story: *no one is so irreplaceable in this world.* 
 
This Spring, I probably gave a little too much to my Health Analytics class, to the point of being self-sacrificing. This shouldn’t be a reflection of the class - they were great and really whip smart - I just tend to give a little too much. As a result, I was pretty drained by the time I got to Summer quarter. I’d definitely overdrawn on giving - I was pretty wiped out through the summer. Being overdrawn actually meant I didn’t have enough energy to teach as well as I would have liked - and I felt worse for this.
 
The lesson I've learned this summer: If you find yourself giving to the point of self-sacrifice, you need to ask yourself why you are sacrificing so much of yourself. Excessive self-sacrifice seems to occur when your [self-esteem is tied to the perception of yourself by other people](http://www.spsp.org/news-center/press-releases/relationship-sacrifice). Meaning, you should question *why* you are self-sacrificing. Is it because you feel like you need the approval of others? No one's approval is worth overworking yourself over.

So, self-sacrifice is ultimately bullshit. Ironically, being self-sacrificing can lead to [feelings of helplessness and resentment](https://greatergood.berkeley.edu/article/item/when_are_you_sacrificing_too_much_in_your_relationship) from the people you are sacrificing yourself for.  Additionally, being [highly proactive and championing change can actually have negative effects](https://hbr.org/2019/08/when-to-take-initiative-at-work-and-when-not-to?) if your actions are perceived as a threat to your organizational culture. There’s a reason why change management is important. No one person can be a revolution - it takes others to do so. It shouldn’t fall to just being on you. 

You need to take care of yourself and protect yourself from the takers. As Faith Harper writes in [Unf#ck Your Adulting](https://microcosmpublishing.com/catalog/books/6860), “taking care of yourself does the world a favor”. Taking care of yourself means that you can do good in the world sustainably, and continue to do it, rather than burning out.

Understand that the notion of true giving is not rooted in self-sacrifice. [Giving is in the spirit of generosity](https://medium.com/@janfortune/how-to-be-a-giver-not-a-sacrificer-a55bf354fcf7); in contrast, self-sacrifice is more akin depleting one’s own resources. As a giver, your generosity should be recognized and not exploited.

One thing to be aware of as a giver is [passion exploitation](https://www.kqed.org/arts/13857471/artist-passion-exploitation-duke-study), where people and organizations will take advantage of you because of your passion for a subject as an opportunity to [pay you much less than you’re worth](https://www.fuqua.duke.edu/duke-fuqua-insights/kay-passion-exploitation).  Such an attitude is prevalent in creative industries, where one is encouraged to work for free or “exposure” (I don’t really do soundtrack work any more because of this). As if being a poor artist or creative was a privilege. Such situations will drain your passion and your energy and burn you out with nothing to show for it. Again, you have to keep something for yourself.
 
If you want to continue to do good in the world, you must take care of yourself. This is especially the case in a toxic work culture. You have to build reserves - never give more of yourself than you can. Especially do not do this in a work setting. It is amazing how self-sacrifice can become the status-quo and what is expected of workers. No one is well off because of that. Toxic work cultures encourage this: [crunch time as the norm at game studios](https://kotaku.com/crunch-time-why-game-developers-work-such-insane-hours-1704744577), [overwork at Japanese Black Companies](https://www.vice.com/en_us/article/3b5e7k/the-japanese-are-dying-for-work), even in the [non-profit sector](https://bloomerang.co/blog/7-ways-to-prevent-passion-exploitation-at-your-nonprofit/).

In short, I believe in kindness and giving. But the kindness and giving must be sustainable. You must defend yourself from those who would take more than they give, and avoid being exploited by those who see your passion as something exploitable. Identifying these people and organizations and saying no is key to taking care of yourself while making things better for others. Don’t feel guilty about this. Don’t make self-sacrifice part of your identity or job description. 

## Resources

- [*Give and Take*](https://www.adamgrant.net/give-and-take) - this is the book that opened my eyes to the power of being a social giver.
- [*Unfuck Your Adulting*](https://microcosmpublishing.com/catalog/books/6860) - this book by Faith Harper is full of good advice about navigating situations, emotions, and taking responsibility for what you can take responsibility for.
- [*How to be a giver, not a self-sacrificer*](https://medium.com/@janfortune/how-to-be-a-giver-not-a-sacrificer-a55bf354fcf7) - talks about giving in the spirit of generosity, and not self-sacrifice. Again, keep something for yourself.
- [*When to take initiative at work, and when not to*](https://hbr.org/2019/08/when-to-take-initiative-at-work-and-when-not-to?)
- [*Avoiding Burnout: Tips for self-care*](https://wonderscounseling.com/burnout/)  - again, very good tips on taking care of yourself, because no one else will.