---
title: Self Care and Self Compassion in Academia
author: ~
date: '2018-06-05'
slug: self-care-and-self-compassion-in-academia
categories: []
tags: [self-care self-compassion]
description: |
   Why self-care is important in academia.   
output:
  distill::distill_article:
    self_contained: true
---

> *Note: I am not writing the following to complain, or excuse any past behavior. I am writing this just to be honest and transparent about my current struggles in academia. I hope it helps someone, or encourages other to seek help.*

I have to confess that I haven't really been feeling all that well the past few months. Right now I am plagued with feelings that I am doing my work as an Assistant Professor wrong. I struggle with this persistent voice in my head that even when I am working at full tilt and beyond, that it's not enough. 

For most of my life, I have had chronic depression. I am a high functioning depressive; I have managed to get things done when I am depressed. However, this effort comes at the cost of self-care. I really think that some past posts have really come from a place of high stress and high anxiety. I apologize for [the harsh tone of this post](http://laderast.github.io/2018/01/15/if-you-want-to-talk-with-me-for-an-informational-interview/). I am also struggling with burnout at this point. I am beginning to feel like a lot of my efforts to encourage interdisciplinary collaborations are not feeling very productive. Part of this has to do with internal politics.

I don't think my depression is an excuse for my past behavior. The lack of self-care, however, is a major cause. When I don't take care of myself, I reach a place of high stress and high anxiety and I can't think straight. If I have been hurtful or bullying to others in any way because of this, I apologize. 

I still struggle with impostor syndrome. I do think that in many ways, this struggle has helped me become more compassionate as a teacher, remembering what concepts I struggled with. I have been trying my best to keep up with the added responsibilities of a faculty member: mentoring students, writing new course material, doing outreach, and also trying to keep the lights on by doing research (I won't get into grant writing here; that's another major depressive kettle of fish). I feel like I've currently been a disappointment as a faculty member so far. 

I am currently in therapy, which has been very helpful in understanding what problems I can address and what problems that are currently endemic to the academic system. I don't know of any other field where one can accomplish a lot yet still feel like a failure. 

The hardest thing for me is saying no, especially to students. But I realize that I can't really be my best for students without taking care of myself. That balance between being considerate of others and also being considerate of my self is something that I am struggling with as a faculty member. 

I guess my point being is that I need to reframe saying no as being protective of myself and my current students rather than registering the disappointment when I say no. I'd like to help people, but I can help people better when I'm feeling well and better. Part of this may be coming to grips that academia may not be my place in the world if it demands that I sacrifice my mental health just to stay where I am.

So for the time being, I'd like to focus on getting better and feeling better. For your sake and mine. I will try to welcome newcomers to data science the best I can - just realize that what I may be able to do for you is a little limited right now. 