---
title: "BMI 569: Data Analytics"
description: |
  Practical coursework in R/SQL for our hybrid Data Analytics Course taught with Kaiser Permanente.
author: [Ted Laderas, Mark Klick, Aaron Coyner]
categories: ["course", "datascience", "R"]
date: 2020-04-20
output:
  distill::distill_article:
    self_contained: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Course Description

Practical coursework in R/SQL for our hybrid Data Analytics Course taught with Kaiser Permanente. This course has been taught from 2013 to the present during summer quarter for students in the Biomedical Informatics program at OHSU.

This repo includes the practical coursework in R/SQL for our hybrid Data Analytics Course taught with Kaiser Permanente. This course has been taught from 2013 to the present during summer quarter for students in the Biomedical Informatics program at OHSU.

Please note that this is only half of the course, which also includes discussions on organizational behavior, implementing analytics projects within an organization, and discussions of the LACE score. 

## Learning Objectives:

- Understand the basics of using R/Rstudio
- Learn and apply basic SQL queries to a synthetic patient cohort
- Implement a metric for predicting 30 day hospital readmissions (LACE score) for this patient cohort.
- Learn, understand, and apply simple visualizations to communicate findings
- Understand how to build and interpret logistic regression models

## Link

[Course Website](http://laderast.github.io/AnalyticsCourse/){.btn .btn--info}
[Course Repo](http://github.com/laderast/AnalyticsCourse/){.btn .btn--info}

## Licensing

This course material is released under an Apache 2.0 License.
