---
title: Reframing Impostor Syndrome as the Road to Mastery
author: ~
date: '2018-12-13'
slug: reframing-impostor-syndrome-as-being-on-the-road-to-mastery
categories: []
tags: []
description: |
  Some thoughts about impostor syndrome.   
output:
  distill::distill_article:
    self_contained: true
---

At some point in your life in Data Science, you will probably struggle with [impostor syndrome](https://www.apa.org/gradpsych/2013/11/fraud.aspx). We all do - in fact, even though I have used R and have done bioinformatics and data science for more than 15 years, I still struggle with this feeling. As a beginner, the mountain you must climb to master skills in data science seems like a long and impossible one.

Caitlin Hudon, in her post about [dealing with impostor syndrome](https://caitlinhudon.com/2018/01/19/imposter-syndrome-in-data-science/) has this to say about countering impostor syndrome:

> The way that I’ve dealt with imposter syndrome is this: I’ve accepted that I will never be able to learn everything there is to know in data science — I will never know every algorithm, every technology, every cool package, or even every language — and that’s okay. The great thing about being in such a diverse field is that nobody will know all of these things (and that’s okay too!).

I think it's important to try and reframe the feelings of impostor syndrome into something more positive. I think having self-compassion about the difficulties of the learning process can help. 

George Leonard's [*Mastery*](https://www.goodreads.com/book/show/81940.Mastery) is a short book that I think can help provide the antidote to these feelings of fraud and inadequacy. I feel that beginners and learners would feel much better if their instructors would own up to their own personal shortcomings as learners. That is, instead of trying to project the image of the all knowledgable guru, instructors should show themselves as humble, lifelong learners as well. 

In [*Mastery*](https://www.goodreads.com/book/show/81940.Mastery), Leonard talks about our unrealistic expectations and how these expectations can get in the way of actually learning and mastering a craft. We are conditioned by ads, movies, and social media that mastering a craft is a never ending set of ever rising climaxes (cue the [training montage](https://www.youtube.com/watch?v=SPFCHuEegsk)), that we can make continuous and steady progress by working hard enough. 

Mastering a craft takes practice, and lots of it. We must learn to be contented to practice when we are on a plateau and are not making visible progress. As Leonard notes, 

> The Path to Mastery is practice.

Leonard outlines 5 principles that can sustain us in our road to mastery and away from impostor syndrome: **Instruction**, **Practice**, **Surrender**, **Intentionality**, and **The Edge**. I'm trying to map common feelings of impostor syndrome and show how these principles can counteract these feelings.

**Instruction**. Leonard emphasizes the importance in finding good instructors and good mentorship that will help us to grow. Finding good instructors can actually be difficult and finding someone who remembers what it was like to be learning something is important. Avoid those instructors who say things like "it should now be obvious" or are disparaging when you don't understand something. 

> He or she is not necessarily the one that gives the most polished lectures, but rather the *one who has discovered how to involve each student actively* in the process of learning.

*What you can do today*: look at twitter and other forums for your community of learners and support those who give good instruction. Realize that not all teachers are good teachers; leave them and seek better ones if necessary.

**Practice**. Practice for practices' sake. Deliberate practice where you slowly build up your understanding and perceptions is important to your growth.

> Where in our upbringing, our schooling, our career are we taught to value, to enjoy, even to love the plateau, the long stretch of diligent effort with no seeming progress?

*What you can do today*: Join communities of practice such as Tidy Tuesday and share your learning with others. Tidy Tuesday is extremely friendly and encouraging for beginners. Learn together and grow together. These are safe communities to share knowledge.

**Intentionality**. This goes hand in hand with practice. Deliberate practice requires visualizing your process and guiding yourself gently. 

> Intentionality fuels the master's journey. Every master is a master of vision. 

*What you can do today*: find small exercises and projects that help you reinforce what you've learned so far. Find people's code and vignettes and modify them until you understand what they've done and how they structured their work. 

**Surrender**. At some point, you will have to give up your own social position as an expert to grow as a learner. When this happens, you must be willing to risk that standing to progress further. Leonard talks about a karate master learning aikido who was not willing to start from scratch, which impeded his learning. For many of us academics, being willing to abandon the comfort of what we have learned is especially difficult. We feel like we are risking our own social standing and reputation. 

> For the master, surrender means there are no experts. There are only Learners.

*What you can do today*: be humble when faced with new concepts (for many impostor syndrome sufferers this is not the hard part). Recognize when you need to grow and when you have to leave old concepts behind. 

**The Edge**. This is where things are undefined and scary. Still, part of the journey to mastery is a willingness to push your thoughts to beyond the horizon of what you thought was possible. 

> The trick here is not only to test the edges of the envelope, but also to walk the fine line between endless, goalless practice and those alluring roles that appear along the way.

*What you can do today*: Identify some goals that are just beyond your current skillset and be willing to push your learning to that point. 

Leonard maintains that true mastery is not due to innate talent. True mastery is due to tenacity and perserverance in the face of difficult learning. In fact, he suggests that learning things too easily means that you might lack perserverance when the going gets rough and your progress slows. He maintains that someone who perseveres will "have learned whatever [they] are practicing to the marrow of [their] bones."

## Encouraging Mastery as a Community

I think Caitlin's [prescriptions for community wide suggestions for reducing impostor syndrome](https://caitlinhudon.com/2018/01/19/imposter-syndrome-in-data-science/) are wonderful. Especially the advice to "Get comfortable with I don't know". Normalizing "I don't know" within a community is incredibly important to making a psychologically safe learning environment. 

To encourage learners, I think that creating a community of practice and helpfulness is vitally important to give new learners the support they need. When communities take responsibility for the learning of their members, something magic happens. Learning no longer feels lonely and there is no shame when you don't immediately grasp a concept. Patience becomes the norm and people become more confident. 

For me, this is the true value of schools and universities. To get the most out of online learning, you need to participate within a community that encourages you to learn further. Be on the pathway to mastery by participate within learning communities.

## Further Reading

Mastery: https://www.goodreads.com/book/show/81940.Mastery